### ISSUE TITLE
Enemies - Detection

### ISSUE THREAD

**Issue by cladur** [cladur/silence#117]
- [x] State Machine for enemy ("patrolling", "przyglądanie się")
- [x] If enemy can see the player for x amount of time, the stops walking and goes to "przyglądanie się" state, in which he stays for a while
- [x] UI slider on top of enemy's head that shows his detection level

**Comment by a3cb** [comment]
[ ] distracted state
[ ] dead state

**Comment by a3cb** [comment]
- [ ] Distracted state
- [ ] Dead state

**Comment by Maerorr** [comment]
![enemy state machien](https://github.com/cladur/silence/assets/48598901/60230e6f-f333-435b-93ed-96a9cc705ef4)
this illustrates how the enemies *should* work, but if some bug appears ill fix it.
