### ISSUE TITLE
Greetings from Memory Leaks

### ISSUE THREAD

**Issue by Erulathra** [cladur/silence#121]
[You're pretty good](https://www.youtube.com/watch?v=elIxCkdFChw)

**Comment by cladur** [comment]
![1558668182414](https://github.com/cladur/silence/assets/17687087/e64e2d6b-80ea-4116-b53d-2db4d105649b)
L…Look out, Snake!
Your source code is stored on a public repository and with a permissive license!!!

**Comment by Kurogamin** [comment]
zamykam
