### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by cladur** [cladur/silence#159]
We need basic HUD with:
- [x] crosshair for hacker,
- [x] text like "Press [E] to interact" for both agent and hacker,
- [x] entities inside game world that triggers some message when the player walks into them.

For example, agent should always have a text hint to press left click when he can kill the enemy. But he should only get the message on how to crouch somewhere at the start of the game, when he walks into `SphereCast`.

**Comment by Maerorr** [comment]
first two things are already done, the last one will be implemented alongside such elements.
