### ISSUE TITLE
Hacker - CCTV Camera

### ISSUE THREAD

**Issue by cladur** [cladur/silence#187]
- [x] make the CCTV camera rotate, when hacker moves it
- [x] let camera be marked (with right click zoom)
- [x] add highlight to it (on hover)

**Comment by Kurogamin** [comment]
- [x] limit camera rotation

**Comment by cladur** [comment]
- [ ] camera can detect agent and hacker
- [ ] camera has green / red light which visualizes if it is detecting something (picrel) (could be done with just a Billboard, not the actual Light component)

![camera3](https://github.com/cladur/silence/assets/17687087/947a170e-0319-42b1-86aa-f924e1e40afa)
