### ISSUE TITLE
Enemy detection improvements

### ISSUE THREAD

**Issue by cladur** [cladur/silence#188]
- [x] hacker's robot should be detectable, just like the agent (but slower)
- [x] tweak the detection rate - it should be faster
- [x] change detection rate based on agent's distance and stance (standing / crouching)
- [x] check if enemy can just stand, without walking (and if we can't, then implement it)
- [x] make a lot of cvar's for detection rate's

**Comment by Maerorr** [comment]
Zrobione, zamykam. Jak będą jakieś problemy to naprawię.
