### ISSUE TITLE
Hacking - Various improvements

### ISSUE THREAD

**Issue by cladur** [cladur/silence#247]
Exploding Box
- [x] makes broken electronics sounds sort of like [this](https://youtu.be/uRnxSwukW2o) or [that](https://youtu.be/SABs8wSjw0w)
- [x] has some occasional particle sparks coming off of it

Hacker
~- [ ] needs to hold the button for a while in order to hack~
- [x] when he presses the hacking button, a hacking sound plays
- [x] every Interactable object has 3D GUI over it (or IMO better to the right of it? since we already have the "marked" arrow over those?) that contains the hacking button and the name of the action (for ex. explode, move, control)
~- [ ] (MAYBE, IDK) some part of the UI changes as the process of hacking continues? for ex. a button gets smaller or a horizontal slider fills up over the rectangle with text in it. IMO I think the slider would look better.~

I think we could reuse that UI billboard idea for the agent later, for his interaction with the button, jumping on ledges or enemy killing.

Mockup of the UI
<img width="671" alt="image" src="https://github.com/cladur/silence/assets/17687087/0320da6f-6b6f-410f-8ee9-ae4fbb20ccd6">

**Comment by Maerorr** [comment]
zamykam, jest już super
