### ISSUE TITLE
Enemy - More robust detection

### ISSUE THREAD

**Issue by cladur** [cladur/silence#269]
## Detection near the enemy
From what I remember there's a SphereCast in the Enemy that previously detected the player if he was behind / near the enemy?
Bring that SphereCast back, but move it a bit forward, so that the enemy doesn't react to the player if he's behind him, but will react if the player is full in front or to the side.

## Keeping the close detection fair
With that near-instant detection when the player is close, we'll need to be more careful with how the enemy turns around.
We don't want the player to walk behind the enemy, only for him to turn at the last moment and detect him.

### When distracted
I think this could be solved by a second SphereCast placed behind the enemy. If the player were to enter it, the enemy would delay to transition to `Patrolling` state by a couple seconds.

That is, if the player is behind the enemy, we delay enemy's next action, giving the player bigger time window to strike.

I think this delay is only necessary for the distracted state, since we don't want the enemy to stop moving or something when he's patrolling.

### During patrolling

I think it just comes down to how we lay down the enemy's path inside the editor. If we're just assigning two points to the path, obviously the enemy is going to do 180 turns. We should just bring the number of path points up and that should solve it.

- [x] Bring detection SphereCast back, move it forward a bit.
- [x] Increase the enemy detection rate and pull it out to CVar, if it's not already done.
- [x] Add delay to enemy's exiting out of the `Distracted` state, if there's a player behind him.

**Comment by Maerorr** [comment]
all the detections rates are in cvars already
