### ISSUE TITLE
UI - More visible detection

### ISSUE THREAD

**Issue by cladur** [cladur/silence#288]
- [x] Lower the detection meters for the enemy and camera, and make them a bit bigger.
- [x] Make them fully 2D with 3D to screenspace shenanigans.
- [ ] Instead of rectangular bar, make it two triangles, that are no top of each other, like in picrel.
- [ ] If the thing that spots is isn't visible by us(1), place the detection thingy on a screenspace radial circle (?), that rotates with the player's view.
- [ ] If the detection is over 50% make the detection indicator yellow.

(1) Maybe we can do this by doing the 3D to screenspace operation, and if the coordinates are not inside [-1, 1] then we know the detection indicator wouldn't be visible?

<img width="687" alt="image" src="https://github.com/cladur/silence/assets/17687087/92912735-bace-4b98-b507-ac4cb5352b1f">

**Comment by Maerorr** [comment]
` If the thing that spots is isn't visible by us(1), place the detection thingy on a screenspace radial circle (?), that rotates with the player's view.` some explanatrions please

**Comment by Maerorr** [comment]
additionally i was thinking about a "screen flash" that triggers the same way as the detection sound.
