### ISSUE TITLE
TexturedCubeInstance

### ISSUE THREAD

**Issue by cladur** [cladur/silence#290]
ECS Component, sort of like `ModelInstance`, but instead of taking a model, you can drag and drop onto it 6 set of textures, each one for different cube face (set of textures, because there's albedo, roughness, normal, etc.).
There would also be two toggles:
- [ ] `Single Texture` to use one texture for all faces instead,
- [ ] `Scale UV`, like in `ModelInstance` so that the textures would tile instead of being stretched.

**Comment by a3cb** [comment]
not done according to description

**Comment by Kurogamin** [comment]
i dont care
