### ISSUE TITLE
Animacja przeciwnika nie zmienia się przy zmianie stanu na stacjonarne patrolowanie ( możliwe że między innymi również)

### ISSUE THREAD

**Issue by cladur** [cladur/silence#308]
Animacja przeciwnika nie zmienia się przy zmianie stanu na stacjonarne patrolowanie ( możliwe że między innymi również)

**Comment by Kurogamin** [comment]
nie dziala

**Comment by cladur** [comment]
> nie dziala

![co-ty-pierdolisz-posluchaj-co-ty-pierdolisz](https://github.com/cladur/silence/assets/17687087/c6bfeef8-2594-4763-91b5-1a675e564686)
