### ISSUE TITLE
UI fix

### ISSUE THREAD

**Issue by cladur** [cladur/silence#33]
UI doesn't work anymore after last huge merge.

**Comment by Maerorr** [comment]
widziałem, że w sprite_draw @cladur zrobiłeś klasę SpriteDraw ale wszystkie funkcje tworzące sprity i pushujące je do odpowiednich vectorów zostały osobno. Czy zostawić te funkcje tak jak są, po prostu w namespacie czy wciągnąć je do klasy SpriteDraw? 
One i tak będą void i nic nie zmieniały w SpriteDraw, tylko np. klasa mogłaby wtedy przechowywać obecną scenę do której te sprity będą pushowane.

**Comment by cladur** [comment]
Musiałem przypadkowo zostawić ten namespace.
IMO trzeba raczej wciągnąć te funkcje do klasy `SpriteDraw`, która będzie miała swoją instancję w każdym `RenderScene` - podobnie jak w przypadku już obecnego `DebugDraw`.
Potem jakby ktoś by chciał z tych metod skorzystać np. w scenie to wywołałby `get_render_scene().sprite_draw.draw_sprite_billboard(...)`.

**Comment by Maerorr** [comment]
tylko że sprite draw raczej nie powinno być używane bezpośrednio ze wszystkimi klasami UI'owymi jakie mamy.

**Comment by Maerorr** [comment]
Dodatkowy problem jest taki że elementy ui nie mogą być tak po prostu stworzone jak sprity tylko muszą być przechowywane np. guziki/anchory żeby nimi zarządzać tak jak to robiłem w tym demo ui.

**Comment by cladur** [comment]
Może można by było zrobić klasę `UserInterface`, która była by wewnątrz `Scene`, przechowywała by elementy UI i co klatkę rysowała je (czyli wywoływała metody `draw()` tych UIElementów, które dodają sprite'y do `SpriteDraw`?)

**Comment by Maerorr** [comment]
No nie wiem jak to rozwiązać. Wydaje mi się że końcowo powinno być kilka 'skryptów' które zarządzają osobno różnymi zbiorami elementów np. hud agenta + hud hackera, menu pauzy i wszystkie jego zakładki etc.

No może że masz na myśli że każda scena miałaby jakąś `unordered_map` elementów ui które by rysowała ale którymi zarządzałyby specjalne skrypty.

anyways, na razie zrobię to w taki sposób żeby działało ze scenami.
scena będzie miała swoje `std::vector<TransparentObject>` a nad rozwiązaniem problemu opisanego powyżej pomyślę jak wszystko będzie działać.
