### ISSUE TITLE
Physics Systems

### ISSUE THREAD

**Issue by cladur** [cladur/silence#35]
Right now there are two ECS systems that handle physics - `CollisionSystem` and `BSPSystem`.
`CollisionSystem` handles dynamic - dynamic collisions, while `BSPSystem` handles dynamic - static ones.
However with current implementation `BSPSystem` depends on `CollisionSystem` in order to get a list of dynamic entities.
If ECS `World` is supposed to handle all systems automatically, we can't have this interdependence between systems.
We need to rewrite `BSPSystem` so that building and storing BSP tree happens somewhere else and `BSPSystem`'s signature gives it the entities it actually needs instead of borrowing `CollisionSystem`'s ones.

**Comment by cladur** [comment]
I think BSP tree should be stored inside `Scene`. It would be built after the scene is created and it's entities are loaded from the file.
For now calling the `build_tree()` could be done at the end of `Scene::load_from_file()` I think.
In order for `BSPSystem` to access the BSP tree, we would need to add a getter inside `World` class, that would give back a reference to the scene.

**Comment by cladur** [comment]
@Maerorr Also, [here's a cool video](https://www.youtube.com/watch?v=wLHXn8IlAiA) that quickly explains how BSP works.

**Comment by Maerorr** [comment]
Obecnie wszystko już jest zrobione tak jak opisane powyżej. Problem jest taki, że okazało się że sam BSPSystem nie działa, a dokładnie budowanie drzewa. Pisałem do @Merloran i powiedział że zrobi fixa, pewnie jak upora się z animacją.
Czy robić PR teraz tylko z zakomentowanym updatem BSPSystemu?

**Comment by cladur** [comment]
Tak, zrób.
