### ISSUE TITLE
ECS Lights

### ISSUE THREAD

**Issue by cladur** [cladur/silence#56]
- [x] Add drawing arrows and cones shapes to DebugDraw
- [x] Add Light Component that will store stuff like `color`, `strength`, `direction` (for Spotlight and Directional lights) and etc.
- [x] Add Light Component to Inspector
- [x] Visualize Light Component with DebugDraw
- [x] Hook that up with rendering (just point lights for now)

**Comment by Kurogamin** [comment]
[ ] Enable/Disable light debug drawing using cvar
