### ISSUE TITLE
Deferred Rendering - Improved lights

### ISSUE THREAD

**Issue by cladur** [cladur/silence#82]
Point lights right now are pretty basic, for ex. you can't edit their strength, we need to add a parameter for that.
Spot lights are absent, we need to add them as well.

On top of that, instead of calculating each light in the scene for each pixel, we should create light volumes (meshes) that represent which regions of image a light actually affects, and then only do the calculations for those spots.

https://learnopengl.com/Advanced-Lighting/Deferred-Shading
https://www.gamedev.net/forums/topic/711348-best-practice-for-treating-light-volumes-in-deferred-lighting-pipline/5444071/

**Comment by cladur** [comment]
Point lights and their light volumes are done for now.
Now we need to do the same for the spotlights.

**Comment by a3cb** [comment]
- [ ] spotlight

**Comment by cladur** [comment]
We still need cone for drawing spotlight
